# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YWokEFaplkGmXjHAtwg5l9kyBsYfl-L_
"""

print("hello github world here is my first project")
